//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tisinalite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TisinaliteDBEntities : DbContext
    {
        private static TisinaliteDBEntities _context;
        public TisinaliteDBEntities()
            : base("name=TisinaliteDBEntities")
        {
        }
        public static TisinaliteDBEntities GetContext()
        {
            if (_context == null)
                _context = new TisinaliteDBEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersOfGroups> UsersOfGroups { get; set; }
    }
}
